# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/sort_two.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/sort_four.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/sort_eight.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/response_buffer.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/refresh_tracker.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/cpu_buffer.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/sort_sixteen.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/schedule_algo.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/scheduled_buffer.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/response_queue.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/command_gen.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/request_tracker.v}
  {C:/Users/Bennett Young/Documents/Memory_Controller/Memory_Controller.srcs/sources_1/new/memory_controller.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top memory_controller -part xc7a35tcpg236-1


write_checkpoint -force -noxdef memory_controller.dcp

catch { report_utilization -file memory_controller_utilization_synth.rpt -pb memory_controller_utilization_synth.pb }
